name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: build with .net 
      run: dotnet build ./src/Checkout.PaymentGateway.sln --configuration Release
    - name: test with .net  
      run: dotnet test ./src/Checkout.PaymentGateway.sln --configuration Release 
